config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  resource :user, as: 'users' do
    collection do
      get :login   # /user/login
    end
  end

  resource :session, only: %i[create destroy]

  resources :orders, only: [:create] do
    member do
      get :checkout
      post :pay
    end
  end

  resources :wish_lists do
    member do
      patch :like
      get :buy
    end

    resources :comments, shallow: true, only: %i[create destroy]
  end

  root 'wish_lists#index'
end

app/models/wish_list.rb
# frozen_string_literal: true

class WishList < ApplicationRecord
  acts_as_paranoid

  # validations
  validates :title, presence: true
  validates :description, presence: true

  # relationships
  belongs_to :user
  has_many :comments

  has_many :like_wish_lists
  has_many :liked_users, through: :like_wish_lists, source: :user

  def liked_by?(user)
    liked_users.include?(user)
  end
end

app/controllers/wish_lists_controller.rb
# frozen_string_literal: true

class WishListsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_wish_list, only: %i[edit update destroy show like buy checkout]

  def index
    @wish_lists = current_user.wish_lists
  end

  def new
    @wish_list = WishList.new
  end

  def create
    @wish_list = current_user.wish_lists.build(wish_list_params)

    if @wish_list.save
      redirect_to root_path, notice: '成功新增許願卡！'
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @wish_list.comments.order(id: :desc)
  end

  def edit; end

  def update
    if @wish_list.update(wish_list_params)
      redirect_to root_path, notice: '成功更新許願卡！'
    else
      render :edit
    end
  end

  def destroy
    @wish_list.destroy
    redirect_to root_path, notice: '資料已刪除'
  end

  def like
    if @wish_list.liked_by?(current_user)
      # 移除 like
      current_user.liked_wish_lists.delete(@wish_list)
      render json: { status: 'unliked' }
    else
      # 新增 like
      current_user.liked_wish_lists << @wish_list
      render json: { status: 'liked' }
    end
  end

  def buy; end

  private

  def find_wish_list
    @wish_list = current_user.wish_lists.find(params[:id])
  end

  def wish_list_params
    params.require(:wish_list).permit(:title, :description, :publish_date, :amount)
  end
end

app/views/wish_lists/_form.html.erb
<%= form_with(model: wish_list) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>
  <div>
    <%= f.label :publish_date %>
    <%= f.date_field :publish_date %>
  </div>
  <%= f.submit %>
<% end %>

app/views/wish_lists/buy.html.erb
<h1><%= @wish_list.title %></h1>

<div data-controller="order-amount"
     data-price="<%= @wish_list.amount %>"
     data-action="update-quantity@document->order-amount#updateQuantity"
     >
  單價：<%= @wish_list.amount %>
  ，小計：<span data-order-amount-target="amount"></span>
</div>

<hr>

<%= form_with(url: orders_path, method: 'post', data: { controller: "order-quantity" }) do |f| %>
  <input type="hidden" name="wish_list_id" value="<%= @wish_list.id %>">
  <button data-action="click->order-quantity#decrement">-</button>
  <input data-order-quantity-target="quantity" type="number" name="quantity" value="1" min="1" max="5">
  <button data-action="click->order-quantity#increment">+</button>

  <button>結帳！</button>
<% end %>

app/views/wish_lists/edit.html.erb
<h1>編輯 WishList</h1>

<%= render "form", wish_list: @wish_list %>

app/views/wish_lists/index.html.erb
<h1>許願卡、清單</h1>

<%= link_to "新增許願卡", new_wish_list_path %>

<% @wish_lists.each do |wish_list| %>
  <li>
    <%= link_to "購買", buy_wish_list_path(wish_list) %>
    <%= link_to "編輯", edit_wish_list_path(wish_list) %>
    <%= link_to "刪除", wish_list_path(wish_list), method: "delete", data: {confirm: "確定嗎"} %>
    <%= link_to "#{wish_list.title} (#{wish_list.amount})", wish_list_path(wish_list) %>
  </li>
<% end %>

app/views/wish_lists/new.html.erb
<h1>新增許願卡</h1>

<%= render "form", wish_list: @wish_list %>

app/views/wish_lists/show.html.erb
<section>
  <header>
    <h1>
      <%= @wish_list.title %>
      <button data-controller="favorite-btn"
              data-action="click->favorite-btn#toggle"
              data-id="<%= @wish_list.id %>"
              data-liked="<%= @wish_list.liked_by?(current_user) %>"
              >
        <i class="fa-regular fa-thumbs-up"
           data-favorite-btn-target="icon"></i>
      </button>
    </h1>
  </header>
  <article data-controller="markdown">
    <%= @wish_list.description %>
  </article>

  <%= form_with(model: @comment, url: wish_list_comments_path(@wish_list), local: false) do |f| %>
    <div>
      <div>留言：</div>
      <%= f.text_area :content %><br />
      <%= f.submit "新增留言" %>
    </div>
  <% end %>

  <ul class="comments">
    <%= render @comments %>
  </ul>
</section>

<script>
</script>